"""initial

Revision ID: e591d265b82e
Revises: 
Create Date: 2026-07-20 23:16:06.140956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e591d265b82e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('rol_actual', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_google_id'), 'usuarios', ['google_id'], unique=True)
    op.create_table('changadores_perfiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fotos_trabajos', sa.Text(), nullable=False),
    sa.Column('especialidades', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changadores_perfiles_user_id'), 'changadores_perfiles', ['user_id'], unique=True)
    op.create_table('changas_posts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion_corta', sa.String(length=500), nullable=False),
    sa.Column('fotos', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('barrio', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changas_posts_user_id'), 'changas_posts', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_a_id', sa.String(length=32), nullable=False),
    sa.Column('user_b_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_user_a_id'), 'matches', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_matches_user_b_id'), 'matches', ['user_b_id'], unique=False)
    op.create_table('swipes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swipes_item_id'), 'swipes', ['item_id'], unique=False)
    op.create_index(op.f('ix_swipes_user_id'), 'swipes', ['user_id'], unique=False)
    op.create_table('cotizaciones',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('monto_estimado', sa.Float(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('fecha_disponible', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_por_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_match_id'), 'cotizaciones', ['match_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('autor_id', sa.String(length=32), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_autor_id'), 'mensajes', ['autor_id'], unique=False)
    op.create_index(op.f('ix_mensajes_match_id'), 'mensajes', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_match_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_autor_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_cotizaciones_match_id'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    op.drop_index(op.f('ix_swipes_user_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_item_id'), table_name='swipes')
    op.drop_table('swipes')
    op.drop_index(op.f('ix_matches_user_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_user_a_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_changas_posts_user_id'), table_name='changas_posts')
    op.drop_table('changas_posts')
    op.drop_index(op.f('ix_changadores_perfiles_user_id'), table_name='changadores_perfiles')
    op.drop_table('changadores_perfiles')
    op.drop_index(op.f('ix_usuarios_google_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
